import { calculateReconstitution, calculateDrip, calculatePump, calculateWeightDose, calculateOxygenDuration, calculateCompoundLiquid, formatPt } from './calculator.js?v=7';
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)]; const num = s => Number($(s).value);

const devices = {
  u100: { scale: 100, label: 'U-100', unit: 'unidades da seringa', note: 'Escala U-100: cada traço representa a graduação selecionada e 100 unidades correspondem a 1 mL. Não confundir com unidades da dose do medicamento.', capacities: [30,50,100], increments: [1,2,.5] },
  u40: { scale: 40, label: 'U-40', unit: 'unidades da seringa', note: 'Escala U-40: 40 unidades correspondem a 1 mL. Use apenas uma seringa identificada como U-40.', capacities: [40], increments: [1,2] },
  ml1: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [1], increments: [.01,.02,.05,.1] },
  ml3: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [3], increments: [.1] },
  ml5: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [5], increments: [.2] },
  ml10: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [10], increments: [.2,.5] },
  ml20: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [20], increments: [1] },
  ml60: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [60], increments: [1,2] }
};
const warningText = { dose_exceeds_vial:'A dose supera o conteúdo total informado para um frasco.', exceeds_syringe:'O volume calculado excede a capacidade do dispositivo selecionado.', very_small_volume:'Volume menor que 0,01 mL. Confirme se o dispositivo permite essa precisão.', not_measurable:'A marca calculada não coincide com a menor graduação selecionada.' };
const alertHtml = (messages, danger=false) => messages.map(m => `<div class="alert ${danger?'alert-error':'alert-warning'}">${m}</div>`).join('');
const invalid = target => { $(target).innerHTML = '<div class="alert alert-error">Revise os campos e informe valores maiores que zero.</div>'; };
const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

function setDeviceOptions(){ const d=devices[$('#syringeType').value]; $('#syringeCapacity').innerHTML=d.capacities.map(v=>`<option value="${v}">${formatPt(v,2)} ${d.scale===1?'mL':'unidades'}</option>`).join(''); $('#syringeIncrement').innerHTML=d.increments.map(v=>`<option value="${v}">${formatPt(v,2)} ${d.scale===1?'mL':'unidade'+(v===1?'':'s')}</option>`).join(''); $('#syringeNote').textContent=d.note; renderReconstitution(); }
function renderScale(d, capacity, increment){ const count=Math.min(240,Math.round(capacity/increment)); const ticks=[]; for(let i=1;i<=count;i++){const value=i*increment, whole=Math.abs(value-Math.round(value))<1e-9, major=whole&&(d.scale===1?value%1===0:value%10===0), medium=whole&&d.scale!==1&&value%5===0; ticks.push(`<i class="${major?'major':medium?'medium':whole?'whole':''}" style="left:${value/capacity*100}%"></i>`);} $('#syringeTicks').innerHTML=ticks.join(''); const labelStep=d.scale===100?10:d.scale===40?5:capacity<=5?1:capacity<=20?5:10; const labels=['<span style="left:0">0</span>']; for(let value=labelStep;value<capacity;value+=labelStep) labels.push(`<span style="left:${value/capacity*100}%">${formatPt(value,2)}</span>`); labels.push(`<span style="left:100%">${formatPt(capacity,2)}</span>`); $('#syringeScaleLabels').innerHTML=labels.join(''); }
function renderReconstitution(){ const d=devices[$('#syringeType').value], capacity=num('#syringeCapacity'), increment=num('#syringeIncrement'); const r=calculateReconstitution({vialMg:num('#vialMg'),finalVolumeMl:num('#finalVolumeMl'),doseMg:num('#doseMg'),scalePerMl:d.scale,syringeCapacity:capacity,syringeIncrement:increment}); if(!r.ok){invalid('#reconAlerts');return;} const danger=r.warnings.some(w=>w==='dose_exceeds_vial'||w==='exceeds_syringe'); $('#reconStatus').textContent=danger?'Requer revisão':r.warnings.length?'Atenção à precisão':'Dentro da capacidade'; $('#reconStatus').className=`status ${danger?'status-error':r.warnings.length?'status-warning':''}`; $('#reconAlerts').innerHTML=alertHtml(r.warnings.map(w=>warningText[w]),danger); $('#scaleResultLabel').textContent=`MARCA NA ESCALA ${d.label}`; $('#scaleResult').textContent=formatPt(r.scaleValue,d.scale===1?3:2); $('#scaleResultUnit').textContent=d.unit; $('#concentrationResult').textContent=`${formatPt(r.concentrationMgMl,3)} mg/mL`; $('#volumeResult').textContent=`${formatPt(r.volumeMl,4)} mL`; $('#capacityResult').textContent=`${formatPt(r.capacityPercent,1)}%`; const p=Math.max(0,Math.min(100,r.capacityPercent)); $('#syringeFill').style.width=`${p}%`; $('#syringeMarker').style.left=`${p}%`; renderScale(d,capacity,increment); $('#reconSummary').textContent=`${formatPt(num('#vialMg'),3)} mg em ${formatPt(num('#finalVolumeMl'),3)} mL → ${formatPt(r.concentrationMgMl,3)} mg/mL. Dose ${formatPt(num('#doseMg'),3)} mg → ${formatPt(r.volumeMl,4)} mL → marca ${formatPt(r.scaleValue,d.scale===1?3:2)} na escala ${d.label}.`; }

function renderDrip(){ const factor=num('#dropFactor'), r=calculateDrip({volumeMl:num('#dripVolume'),hours:num('#dripHours'),minutes:num('#dripMinutes'),dropFactor:factor}); if(!r.ok){invalid('#dripAlerts');return;} $('#dripAlerts').innerHTML=''; $('#dropsResult').textContent=formatPt(r.dropsPerMinute,0); $('#dropsUnit').textContent=factor===60?'microgotas/min':'gotas/min'; $('#dripMlHour').textContent=`${formatPt(r.mlPerHour,1)} mL/h`; $('#dripTime').textContent=`${Math.floor(r.totalMinutes/60)} h ${r.totalMinutes%60?`${r.totalMinutes%60} min`:''}`; $('#dripSummary').textContent=`${formatPt(num('#dripVolume'),1)} mL × ${factor} ÷ ${r.totalMinutes} min = ${formatPt(r.dropsPerMinuteExact,2)}; ajustar para ${r.dropsPerMinute} ${factor===60?'microgotas':'gotas'}/min.`; }
function renderPump(){ const r=calculatePump({volumeMl:num('#pumpVolume'),rateMlHour:num('#pumpRate')}); if(!r.ok){invalid('#pumpAlerts');return;} $('#pumpAlerts').innerHTML=''; $('#pumpTimeResult').textContent=`${r.wholeHours} h ${r.remainingMinutes?`${r.remainingMinutes} min`:''}`; $('#pumpMinutesResult').textContent=`${formatPt(r.totalMinutes,0)} minutos`; $('#pumpVolumeResult').textContent=`${formatPt(num('#pumpVolume'),2)} mL`; $('#pumpRateResult').textContent=`${formatPt(num('#pumpRate'),2)} mL/h`; $('#pumpSummary').textContent=`${formatPt(num('#pumpVolume'),2)} mL ÷ ${formatPt(num('#pumpRate'),2)} mL/h = ${formatPt(r.durationHours,2)} horas.`; }
function renderWeight(){ const raw=$('#maxDoseMg').value.trim(), max=raw===''?null:Number(raw); const r=calculateWeightDose({prescribedMgKg:num('#prescribedMgKg'),weightKg:num('#weightKg'),availableMg:num('#availableMg'),availableVolumeMl:num('#availableVolume'),maxDoseMg:max}); if(!r.ok){invalid('#weightAlerts');return;} const over=r.warnings.includes('exceeds_max_dose'); $('#weightAlerts').innerHTML=over?alertHtml([`A dose calculada (${formatPt(r.doseMg,2)} mg) supera o limite informado (${formatPt(max,2)} mg).`],true):''; $('#weightVolumeResult').textContent=formatPt(r.volumeMl,3); $('#totalDoseResult').textContent=`${formatPt(r.doseMg,2)} mg`; $('#weightConcentrationResult').textContent=`${formatPt(r.concentrationMgMl,3)} mg/mL`; $('#weightSummary').textContent=`${formatPt(num('#prescribedMgKg'),3)} mg/kg × ${formatPt(num('#weightKg'),2)} kg = ${formatPt(r.doseMg,2)} mg. Na concentração ${formatPt(r.concentrationMgMl,3)} mg/mL → ${formatPt(r.volumeMl,3)} mL.`; }
function renderOxygen(){ const r=calculateOxygenDuration({pressureBar:num('#oxygenPressure'),reserveBar:num('#oxygenReserve'),cylinderWaterVolumeL:num('#cylinderVolume'),flowLMin:num('#oxygenFlow')}); if(!r.ok){invalid('#oxygenAlerts');return;} const messages=r.warnings.map(w=>w==='critical_duration'?'Autonomia inferior a 30 minutos. Providencie substituição ou fonte alternativa imediatamente conforme o protocolo.':'Autonomia inferior a 60 minutos. Planeje a substituição do cilindro conforme o protocolo.'); $('#oxygenAlerts').innerHTML=alertHtml(messages,r.warnings.includes('critical_duration')); $('#oxygenTimeResult').textContent=`${r.wholeHours?`${r.wholeHours} h `:''}${r.remainingMinutes} min`; $('#oxygenMinutesResult').textContent=`${formatPt(r.totalMinutes,0)} minutos`; $('#oxygenAvailableResult').textContent=`${formatPt(r.usableOxygenL,1)} L`; $('#oxygenPressureResult').textContent=`${formatPt(r.usablePressureBar,1)} bar`; $('#oxygenSummary').textContent=`(${formatPt(num('#oxygenPressure'),1)} − ${formatPt(num('#oxygenReserve'),1)}) bar × ${formatPt(num('#cylinderVolume'),2)} L ÷ ${formatPt(num('#oxygenFlow'),2)} L/min = ${formatPt(r.totalMinutes,1)} minutos.`; }

const routeNotes = {
  oral: 'Via oral: confira concentração do frasco, gotas/mL quando aplicável, orientação de diluição e dose prescrita.',
  enteral: 'Via enteral: confirme compatibilidade com sonda, diluição/lavagem e protocolo institucional.',
  im: 'Intramuscular: confira volume máximo por sítio, técnica, agulha e restrições da apresentação.',
  sc: 'Subcutânea: confirme volume máximo por sítio, técnica, concentração e se a apresentação permite essa via.',
  ivDirect: 'IV direta: confirme diluente, compatibilidade, concentração final e tempo de administração no protocolo.',
  ivInfusion: 'IV diluída/infusão: confira volume final, estabilidade, compatibilidade e programação de bomba.',
  nebulization: 'Nebulização: confirme diluente, volume final do copo, dispositivo e protocolo.',
  topical: 'Tópica: confirme concentração, área de aplicação, integridade da pele/mucosa e técnica limpa.',
  eyeEar: 'Oftálmica/otológica: confira apresentação estéril, concentração, lado correto e prevenção de contaminação.'
};
const routeLabels = { oral:'Oral', enteral:'Enteral/sonda', im:'Intramuscular', sc:'Subcutânea', ivDirect:'IV direta', ivInfusion:'IV diluída/infusão', nebulization:'Nebulização', topical:'Tópica', eyeEar:'Oftálmica/otológica' };

function enhanceCompoundForm(){
  if($('#compoundRoute')) return;
  $('#compoundMode').closest('.field').insertAdjacentHTML('afterend', `<div class="field-grid compound-route-grid"><div class="field"><label for="compoundRoute">Via de administração</label><select id="compoundRoute"><option value="oral">Oral</option><option value="enteral">Enteral / sonda</option><option value="im">Intramuscular</option><option value="sc">Subcutânea</option><option value="ivDirect">IV direta</option><option value="ivInfusion">IV diluída / infusão</option><option value="nebulization">Nebulização</option><option value="topical">Tópica</option><option value="eyeEar">Oftálmica / otológica</option></select></div><div class="field"><label for="compoundPreparation">Preparo</label><select id="compoundPreparation"><option value="direct">Uso direto da apresentação</option><option value="diluted">Diluído antes da administração</option></select></div></div><div class="field-grid compound-dilution-grid" id="compoundDilutionFields" hidden><div class="field"><label for="compoundSourceVolume">Volume do medicamento usado</label><div class="input-unit"><input id="compoundSourceVolume" type="number" min="0.001" step="any" value="2"><span>mL</span></div></div><div class="field"><label for="compoundFinalVolume">Volume final após diluição</label><div class="input-unit"><input id="compoundFinalVolume" type="number" min="0.001" step="any" value="10"><span>mL</span></div></div></div><div class="context-note route-note" id="compoundRouteNote"></div>`);
  [1,2,3,4].forEach(i=>{
    const field = $(`#compoundMgMl${i}`).closest('.field');
    field.querySelector('label').textContent = 'Concentração por mL';
    field.querySelector('.input-unit span').textContent = '/mL';
    field.insertAdjacentHTML('beforeend', `<select class="component-unit" id="compoundUnit${i}" aria-label="Unidade do componente ${i}"><option value="mg">mg</option><option value="mcg">mcg</option><option value="UI">UI</option><option value="mEq">mEq</option></select>`);
  });
}
function componentInputs(){ return [1,2,3,4].map(i=>({name:$(`#compoundName${i}`).value.trim(),unit:$(`#compoundUnit${i}`)?.value||'mg',concentrationPerMl:num(`#compoundMgMl${i}`)})); }
function syncCompoundTargets(){ const selected=$('#compoundTarget').value; const options=componentInputs().map((c,i)=>c.name?`<option value="${i}">${escapeHtml(c.name)} (${escapeHtml(c.unit)})</option>`:'').join(''); $('#compoundTarget').innerHTML=options || '<option value="0">Componente 1</option>'; if([...$('#compoundTarget').options].some(o=>o.value===selected)) $('#compoundTarget').value=selected; }
function currentCompoundTarget(){ const components=componentInputs(); return components[Number($('#compoundTarget').value)] || components.find(c=>c.name) || {unit:'mg'}; }
function syncCompoundMode(){ const mode=$('#compoundMode').value; const target=currentCompoundTarget(); $('#compoundAmountLabel').textContent=mode==='drops'?'Quantidade em gotas':mode==='target'?`Dose alvo em ${target.unit}`:'Volume administrado'; $('#compoundAmountUnit').textContent=mode==='drops'?'gotas':mode==='target'?target.unit:'mL'; $('#compoundTargetField').hidden=mode!=='target'; renderCompound(); }
function renderCompound(){
  syncCompoundTargets();
  const mode=$('#compoundMode').value, preparation=$('#compoundPreparation')?.value||'direct', route=$('#compoundRoute')?.value||'oral';
  if($('#compoundDilutionFields')) $('#compoundDilutionFields').hidden=preparation!=='diluted';
  if($('#compoundRouteNote')) $('#compoundRouteNote').textContent=`${routeNotes[route]} Confirme prescrição, bula/frasco, via, compatibilidade, diluente e protocolo.`;
  const target=currentCompoundTarget();
  $('#compoundAmountUnit').textContent=mode==='target'?target.unit:mode==='drops'?'gotas':'mL';
  const r=calculateCompoundLiquid({mode,amount:num('#compoundAmount'),dropsPerMl:num('#compoundDropsMl'),targetComponentIndex:Number($('#compoundTarget').value),preparation,sourceVolumeMl:$('#compoundSourceVolume')?num('#compoundSourceVolume'):null,finalVolumeMl:$('#compoundFinalVolume')?num('#compoundFinalVolume'):null,components:componentInputs()});
  if(!r.ok){ $('#compoundAlerts').innerHTML = r.code==='invalid_dilution' ? '<div class="alert alert-error">Revise a diluição: o volume final precisa ser igual ou maior que o volume do medicamento usado.</div>' : '<div class="alert alert-error">Revise os campos e informe valores maiores que zero.</div>'; return; }
  $('#compoundAlerts').innerHTML='';
  $('#compoundVolumeResult').textContent=formatPt(r.volumeMl,3);
  $('#compoundDropsResult').textContent=r.drops===null?'Não informado':`${formatPt(r.drops,1)} gotas`;
  $('#compoundComponents').innerHTML=r.delivered.map(c=>{
    const concentration = r.preparation==='diluted' ? ` conc. final ${formatPt(c.concentrationPerMl,3)} ${escapeHtml(c.unit)}/mL` : ` conc. ${formatPt(c.originalConcentrationPerMl,3)} ${escapeHtml(c.unit)}/mL`;
    return `<div><dt>${escapeHtml(c.name)}</dt><dd>${formatPt(c.dose,3)} ${escapeHtml(c.unit)}<small>${concentration}</small></dd></div>`;
  }).join('');
  const amountUnit=mode==='target'?target.unit:mode==='drops'?'gotas':'mL';
  const main=mode==='target'?`Dose alvo ${formatPt(num('#compoundAmount'),3)} ${amountUnit} ÷ concentração final do componente guia = ${formatPt(r.volumeMl,3)} mL.`:mode==='drops'?`${formatPt(num('#compoundAmount'),1)} gotas ÷ ${formatPt(num('#compoundDropsMl'),1)} gotas/mL = ${formatPt(r.volumeMl,3)} mL.`:`Volume informado: ${formatPt(r.volumeMl,3)} mL.`;
  const prep=r.preparation==='diluted'?`Preparo diluído: ${formatPt(r.sourceVolumeMl,3)} mL do medicamento em volume final de ${formatPt(r.finalVolumeMl,3)} mL.`:'Preparo direto: usa a concentração informada da apresentação.';
  $('#compoundSummary').textContent=`${main} ${prep} Via selecionada: ${routeLabels[route]}. Cada componente é calculado por concentração final por mL × volume administrado.`;
}

$$('[data-tool]').forEach(button=>button.addEventListener('click',()=>{ $$('[data-tool]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));}); $$('[data-panel]').forEach(p=>{const active=p.id===button.dataset.tool;p.hidden=!active;p.classList.toggle('active',active);}); history.replaceState(null,'',`#${button.dataset.tool}`); }));
const oxygenButton=document.createElement('button'); oxygenButton.type='submit'; oxygenButton.className='secondary-button'; oxygenButton.textContent='Calcular autonomia'; $('#oxygenForm').append(oxygenButton);
enhanceCompoundForm();
$('#syringeType').addEventListener('change',setDeviceOptions); $('#reconstitutionForm').addEventListener('input',renderReconstitution); $('#reconstitutionForm').addEventListener('change',renderReconstitution); $('#dripForm').addEventListener('input',renderDrip); $('#dripForm').addEventListener('change',renderDrip); $('#pumpForm').addEventListener('input',renderPump); $('#weightForm').addEventListener('input',renderWeight); $('#oxygenForm').addEventListener('input',renderOxygen); $('#oxygenForm').addEventListener('change',renderOxygen); $('#oxygenForm').addEventListener('submit',event=>{event.preventDefault();renderOxygen();}); $('#compoundMode').addEventListener('change',syncCompoundMode); $('#compoundForm').addEventListener('input',renderCompound); $('#compoundForm').addEventListener('change',renderCompound); $('#compoundForm').addEventListener('submit',event=>{event.preventDefault();renderCompound();});
const theme=$('#themeToggle'); const themeOrder=['light','dark','contrast']; const themeNames={light:'Claro',dark:'Escuro',contrast:'Alto contraste'}; const themeIcons={light:'☀',dark:'☾',contrast:'◐'}; function setTheme(t){if(!themeOrder.includes(t))t='light';document.documentElement.dataset.theme=t;localStorage.setItem('theme',t);const next=themeOrder[(themeOrder.indexOf(t)+1)%themeOrder.length];theme.setAttribute('aria-pressed',String(t!=='light'));theme.setAttribute('aria-label',`Tema atual: ${themeNames[t]}. Ativar ${themeNames[next]}`);$('#themeIcon').textContent=themeIcons[t];$('.theme-label').textContent=themeNames[t];} theme.addEventListener('click',()=>{const current=document.documentElement.dataset.theme;setTheme(themeOrder[(themeOrder.indexOf(current)+1)%themeOrder.length]);}); setTheme(localStorage.getItem('theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));
setDeviceOptions(); renderDrip(); renderPump(); renderWeight(); renderOxygen(); syncCompoundMode(); const hash=location.hash.slice(1); if(['drip','pump','weight','oxygen','compounds'].includes(hash)) $(`[data-tool="${hash}"]`).click();
