import { calculateReconstitution, calculateDrip, calculatePump, calculateWeightDose, formatPt } from './calculator.js';
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)]; const num = s => Number($(s).value);

const devices = {
  u100: { scale: 100, label: 'U-100', unit: 'unidades da seringa', note: 'Escala U-100: cada traço representa a graduação selecionada e 100 unidades correspondem a 1 mL. Não confundir com unidades da dose do medicamento.', capacities: [30,50,100], increments: [1,2,.5] },
  u40: { scale: 40, label: 'U-40', unit: 'unidades da seringa', note: 'Escala U-40: 40 unidades correspondem a 1 mL. Use apenas uma seringa identificada como U-40.', capacities: [40], increments: [1,2] },
  ml1: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [1], increments: [.01,.02,.05,.1] },
  ml3: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [3], increments: [.1] },
  ml5: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [5], increments: [.2] },
  ml10: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [10], increments: [.2,.5] },
  ml20: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [20], increments: [1] },
  ml60: { scale: 1, label: 'mL', unit: 'mL na escala', note: 'Seringa graduada em mililitros. Confirme a menor graduação impressa no dispositivo.', capacities: [60], increments: [1,2] }
};
const warningText = { dose_exceeds_vial:'A dose supera o conteúdo total informado para um frasco.', exceeds_syringe:'O volume calculado excede a capacidade do dispositivo selecionado.', very_small_volume:'Volume menor que 0,01 mL. Confirme se o dispositivo permite essa precisão.', not_measurable:'A marca calculada não coincide com a menor graduação selecionada.' };
const alertHtml = (messages, danger=false) => messages.map(m => `<div class="alert ${danger?'alert-error':'alert-warning'}">${m}</div>`).join('');
const invalid = target => { $(target).innerHTML = '<div class="alert alert-error">Revise os campos e informe valores maiores que zero.</div>'; };

function setDeviceOptions(){ const d=devices[$('#syringeType').value]; $('#syringeCapacity').innerHTML=d.capacities.map(v=>`<option value="${v}">${formatPt(v,2)} ${d.scale===1?'mL':'unidades'}</option>`).join(''); $('#syringeIncrement').innerHTML=d.increments.map(v=>`<option value="${v}">${formatPt(v,2)} ${d.scale===1?'mL':'unidade'+(v===1?'':'s')}</option>`).join(''); $('#syringeNote').textContent=d.note; renderReconstitution(); }
function renderScale(d, capacity, increment){ const count=Math.min(240,Math.round(capacity/increment)); const ticks=[]; for(let i=1;i<=count;i++){const value=i*increment, whole=Math.abs(value-Math.round(value))<1e-9, major=whole&&(d.scale===1?value%1===0:value%10===0), medium=whole&&d.scale!==1&&value%5===0; ticks.push(`<i class="${major?'major':medium?'medium':whole?'whole':''}" style="left:${value/capacity*100}%"></i>`);} $('#syringeTicks').innerHTML=ticks.join(''); const labelStep=d.scale===100?10:d.scale===40?5:capacity<=5?1:capacity<=20?5:10; const labels=['<span style="left:0">0</span>']; for(let value=labelStep;value<capacity;value+=labelStep) labels.push(`<span style="left:${value/capacity*100}%">${formatPt(value,2)}</span>`); labels.push(`<span style="left:100%">${formatPt(capacity,2)}</span>`); $('#syringeScaleLabels').innerHTML=labels.join(''); }
function renderReconstitution(){ const d=devices[$('#syringeType').value], capacity=num('#syringeCapacity'), increment=num('#syringeIncrement'); const r=calculateReconstitution({vialMg:num('#vialMg'),finalVolumeMl:num('#finalVolumeMl'),doseMg:num('#doseMg'),scalePerMl:d.scale,syringeCapacity:capacity,syringeIncrement:increment}); if(!r.ok){invalid('#reconAlerts');return;} const danger=r.warnings.some(w=>w==='dose_exceeds_vial'||w==='exceeds_syringe'); $('#reconStatus').textContent=danger?'Requer revisão':r.warnings.length?'Atenção à precisão':'Dentro da capacidade'; $('#reconStatus').className=`status ${danger?'status-error':r.warnings.length?'status-warning':''}`; $('#reconAlerts').innerHTML=alertHtml(r.warnings.map(w=>warningText[w]),danger); $('#scaleResultLabel').textContent=`MARCA NA ESCALA ${d.label}`; $('#scaleResult').textContent=formatPt(r.scaleValue,d.scale===1?3:2); $('#scaleResultUnit').textContent=d.unit; $('#concentrationResult').textContent=`${formatPt(r.concentrationMgMl,3)} mg/mL`; $('#volumeResult').textContent=`${formatPt(r.volumeMl,4)} mL`; $('#capacityResult').textContent=`${formatPt(r.capacityPercent,1)}%`; const p=Math.max(0,Math.min(100,r.capacityPercent)); $('#syringeFill').style.width=`${p}%`; $('#syringeMarker').style.left=`${p}%`; renderScale(d,capacity,increment); $('#reconSummary').textContent=`${formatPt(num('#vialMg'),3)} mg em ${formatPt(num('#finalVolumeMl'),3)} mL → ${formatPt(r.concentrationMgMl,3)} mg/mL. Dose ${formatPt(num('#doseMg'),3)} mg → ${formatPt(r.volumeMl,4)} mL → marca ${formatPt(r.scaleValue,d.scale===1?3:2)} na escala ${d.label}.`; }

function renderDrip(){ const factor=num('#dropFactor'), r=calculateDrip({volumeMl:num('#dripVolume'),hours:num('#dripHours'),minutes:num('#dripMinutes'),dropFactor:factor}); if(!r.ok){invalid('#dripAlerts');return;} $('#dripAlerts').innerHTML=''; $('#dropsResult').textContent=formatPt(r.dropsPerMinute,0); $('#dropsUnit').textContent=factor===60?'microgotas/min':'gotas/min'; $('#dripMlHour').textContent=`${formatPt(r.mlPerHour,1)} mL/h`; $('#dripTime').textContent=`${Math.floor(r.totalMinutes/60)} h ${r.totalMinutes%60?`${r.totalMinutes%60} min`:''}`; $('#dripSummary').textContent=`${formatPt(num('#dripVolume'),1)} mL × ${factor} ÷ ${r.totalMinutes} min = ${formatPt(r.dropsPerMinuteExact,2)}; ajustar para ${r.dropsPerMinute} ${factor===60?'microgotas':'gotas'}/min.`; }
function renderPump(){ const r=calculatePump({volumeMl:num('#pumpVolume'),rateMlHour:num('#pumpRate')}); if(!r.ok){invalid('#pumpAlerts');return;} $('#pumpAlerts').innerHTML=''; $('#pumpTimeResult').textContent=`${r.wholeHours} h ${r.remainingMinutes?`${r.remainingMinutes} min`:''}`; $('#pumpMinutesResult').textContent=`${formatPt(r.totalMinutes,0)} minutos`; $('#pumpVolumeResult').textContent=`${formatPt(num('#pumpVolume'),2)} mL`; $('#pumpRateResult').textContent=`${formatPt(num('#pumpRate'),2)} mL/h`; $('#pumpSummary').textContent=`${formatPt(num('#pumpVolume'),2)} mL ÷ ${formatPt(num('#pumpRate'),2)} mL/h = ${formatPt(r.durationHours,2)} horas.`; }
function renderWeight(){ const raw=$('#maxDoseMg').value.trim(), max=raw===''?null:Number(raw); const r=calculateWeightDose({prescribedMgKg:num('#prescribedMgKg'),weightKg:num('#weightKg'),availableMg:num('#availableMg'),availableVolumeMl:num('#availableVolume'),maxDoseMg:max}); if(!r.ok){invalid('#weightAlerts');return;} const over=r.warnings.includes('exceeds_max_dose'); $('#weightAlerts').innerHTML=over?alertHtml([`A dose calculada (${formatPt(r.doseMg,2)} mg) supera o limite informado (${formatPt(max,2)} mg).`],true):''; $('#weightVolumeResult').textContent=formatPt(r.volumeMl,3); $('#totalDoseResult').textContent=`${formatPt(r.doseMg,2)} mg`; $('#weightConcentrationResult').textContent=`${formatPt(r.concentrationMgMl,3)} mg/mL`; $('#weightSummary').textContent=`${formatPt(num('#prescribedMgKg'),3)} mg/kg × ${formatPt(num('#weightKg'),2)} kg = ${formatPt(r.doseMg,2)} mg. Na concentração ${formatPt(r.concentrationMgMl,3)} mg/mL → ${formatPt(r.volumeMl,3)} mL.`; }

$$('[data-tool]').forEach(button=>button.addEventListener('click',()=>{ $$('[data-tool]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));}); $$('[data-panel]').forEach(p=>{const active=p.id===button.dataset.tool;p.hidden=!active;p.classList.toggle('active',active);}); history.replaceState(null,'',`#${button.dataset.tool}`); }));
$('#syringeType').addEventListener('change',setDeviceOptions); $('#reconstitutionForm').addEventListener('input',renderReconstitution); $('#reconstitutionForm').addEventListener('change',renderReconstitution); $('#dripForm').addEventListener('input',renderDrip); $('#dripForm').addEventListener('change',renderDrip); $('#pumpForm').addEventListener('input',renderPump); $('#weightForm').addEventListener('input',renderWeight);
const theme=$('#themeToggle'); function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem('theme',t);const dark=t==='dark';theme.setAttribute('aria-pressed',String(dark));theme.setAttribute('aria-label',dark?'Ativar modo claro':'Ativar modo escuro');$('#themeIcon').textContent=dark?'☀':'☾';} theme.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')); setTheme(localStorage.getItem('theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));
setDeviceOptions(); renderDrip(); renderPump(); renderWeight(); const hash=location.hash.slice(1); if(['drip','pump','weight'].includes(hash)) $(`[data-tool="${hash}"]`).click();
